Billing_System/Models/vender.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vender
    {
        public int vender_id { get; set; }
        public string vander_name { get; set; }
        public string mobile_number { get; set; }
        public string city { get; set; }
    }
}

Billing_System/Controllers/VenderController.cs
using Billing_System.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace Billing_System.Controllers
{
    public class VenderController : Controller
    {
        Billing_SystemEntities db = new Billing_SystemEntities();   
        public ActionResult Index()
        {
            List<vender> lst = db.venders.ToList();
            return View(lst);
        }

        public ActionResult Vender()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Vender(vender p)
        {

            db.venders.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult Delete(int id)
        {
            vender tt = db.venders.Find(id);
            db.venders.Remove(tt);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult Edit(int id)
        {
            vender st = db.venders.Find(id);
            return View(st);
        }


        [HttpPost]
        public ActionResult Edit(vender s)
        {
            db.Entry<vender>(s).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}
    

Billing_System/Views/Vender/Edit.cshtml
@model Billing_System.Models.vender
@{
    ViewBag.Title = "Vendor";
    Layout = "~/Views/Shared/MyLayout.cshtml";
}

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css2?family=Baloo+Bhai+2:wght@600&family=Poppins:wght@200&display=swap" rel="stylesheet">

<style>
    .btn {
        margin-inline: 5px;
    }

    .heading-2 {
        text-align: center;
        font-family: 'Times New Roman';
        font-size: 2.5rem;
        color: black;
    }

    label {
        font-weight: bold;
        font-size: 1.2rem;
    }

    input[type="text"],
    input[type="password"],
    input[type="date"],
    select {
        width: 100%;
        padding: 8px;
        margin-top: 5px;
        margin-bottom: 10px;
        box-sizing: border-box;
    }

    .form-group {
        max-width: 600px;
        margin: 0 auto;
    }

    .form-row {
        margin-left: 16%;
    }

    .btn-lg {
        margin-top: 1rem;
    }
</style>

@using (Html.BeginForm())
{
    @Html.HiddenFor(e => e.vender_id);
    <h3 class="heading-2">Vendor Data</h3>
    <div class="">
        <div class=" mb-3 form-group">
            @Html.LabelFor(e => e.vander_name, "Vendor Name")
            @Html.TextBoxFor(e => e.vander_name, new { @class = "form-control", placeholder = "Enter Vendor Name" })
        </div>

        <div class=" mb-3 form-group">
            @Html.LabelFor(e => e.mobile_number, "Mobile Number")
            @Html.TextBoxFor(e => e.mobile_number, new { @class = "form-control", placeholder = "Enter Mobile Number" })
        </div>

        <div class=" mb-3 form-group">
            @Html.LabelFor(e => e.city, "City")
            @Html.TextBoxFor(e => e.city, new { @class = "form-control", placeholder = "Enter City" })
        </div>

        <div class="mb-3 form-group">
            <input type="submit" value="Update" class="btn btn-success btn-lg">
            @Html.ActionLink("Go to table", "Index", null, new { @class = "link-to-table btn btn-danger btn-lg" })
        </div>
    </div>
}

Billing_System/Views/Vender/Index.cshtml
@model IEnumerable<Billing_System.Models.vender>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/MyLayout.cshtml";
}



<!-- Include Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

<style>
    body {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        background-color: #f4f4f4;
    }

    .container {
        margin-top: 20px;
    }

    .table-responsive {
        overflow-y: auto;
        max-height: 350px;
    }

    .btn-sm {
        padding: 0.25rem 0.5rem;
        font-size: 0.875rem;
    }

    .action-links {
        white-space: nowrap;
    }

    thead {
        position: sticky;
        top: 0;
    }
</style>

<div class="container">
    <div class="link-to-table">
        @Html.ActionLink("Go to Form", "Vender", null, new { @class = "btn btn-warning" })
    </div>

    <h2 class="text-center">Vendor List</h2>

    <div class="table-responsive">
        <table class="table table-bordered table-hover">
            <thead class="thead-dark">
                <tr>
                    <th>Vender Name</th>
                    <th>MObile Number</th>
                    <th>City</th>
                    <th>Action</th>

                </tr>
            </thead>

            <tbody>
                @{
                    int i = 1;
                }
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.vander_name</td>
                        <td>@item.mobile_number</td>
                        <td>@item.city</td>
                   
                        <td class="action-links">
                            @Html.ActionLink("Delete", "Delete", new { @id = item.vender_id }, new { @class = "btn btn-danger" })
                            @Html.ActionLink("Edit", "Edit", new { @id = item.vender_id }, new { @class = "btn btn-success" })
                        </td>
                    </tr>
                    i++;
                }
            </tbody>
        </table>
    </div>
</div>

<!-- Include Bootstrap JS and Popper.js (required for Bootstrap) -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

Billing_System/Views/Vender/Vender.cshtml
@model Billing_System.Models.vender
@{
    ViewBag.Title = "Vendor";
    Layout = "~/Views/Shared/MyLayout.cshtml";
}

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css2?family=Baloo+Bhai+2:wght@600&family=Poppins:wght@200&display=swap" rel="stylesheet">

<style>
    .btn {
        margin-inline:5px;
    }

    .heading-2 {
        text-align: center;
        font-family: 'Times New Roman';
        font-size: 2.5rem;
        color: black;
    }

    label {
        font-weight: bold;
        font-size: 1.2rem;
    }

    input[type="text"],
    input[type="password"],
    input[type="date"],
    select {
        width: 100%;
        padding: 8px;
        margin-top: 5px;
        margin-bottom: 10px;
        box-sizing: border-box;
    }

    .form-group {
        max-width: 600px;
        margin: 0 auto;
    }

    .form-row {
        margin-left: 16%;
    }

    .btn-lg {
        margin-top: 1rem;
    }
</style>

@using (Html.BeginForm())
{
    <h3 class="heading-2">Vendor Data</h3>
    <div class="">
        <div class=" mb-3 form-group">
            @Html.LabelFor(e => e.vander_name, "Vendor Name")
            @Html.TextBoxFor(e => e.vander_name, new { @class = "form-control", placeholder = "Enter Vendor Name" })
        </div>

        <div class=" mb-3 form-group">
            @Html.LabelFor(e => e.mobile_number, "Mobile Number")
            @Html.TextBoxFor(e => e.mobile_number, new { @class = "form-control", placeholder = "Enter Mobile Number" })
        </div>

        <div class=" mb-3 form-group">
            @Html.LabelFor(e => e.city, "City")
            @Html.TextBoxFor(e => e.city, new { @class = "form-control", placeholder = "Enter City" })
        </div>

        <div class="mb-3 form-group">
            <input type="submit" value="Submit" class="btn btn-success btn-lg">
            @Html.ActionLink("Go to table", "Index", null, new { @class = "link-to-table btn btn-danger btn-lg" })
        </div>
    </div>
}